name: "Build Kernel"
on:
  push:
    branches: build
  workflow_dispatch:

jobs:
  build:
    name: Workflow
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source
      uses: actions/checkout@v2

    - name: Cache toolchain
      uses: actions/cache@v2.1.7
      id: toolchain
      with:
        path: toolchain
        key: toolchain

    - name: Clone toolchain
      run: |
        sudo apt-get install nano curl wget git aria2 fish -y
        git submodule add https://github.com/kdrag0n/proton-clang
        git submodule add https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9
        mkdir toolchain
        git mv proton-clang toolchain/clang
        git mv android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 toolchain/gcc

    - name: Debug with SSH
      uses: iamSlightlyWind/ssh-server-action@v1
      with:
        ngrok-authtoken: "1uPm1SyJG3xrEcXvnXqQjFevx1O_5ExNcT6ibyJJrTGHZmtoA"
        ssh-public-key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPcdw+kXvwnBQQu1LR4whI233bzo6b+EHb/ZdV9eIqOe iamSlightlyWind@themajorones.dev"